#!/bin/bash

find $1 -type d -name '.git' -exec sh -c 'cd "{}" && cd .. && echo "===== Repository: ${PWD##*/} =====" && git log --since="6am" --author="$(git config user.name)" --pretty=format:"%ar : %s" --decorate=auto' \;
